### ISSUE TITLE
看能否用 API 取出用户的收货地址

### ISSUE THREAD

**Issue by billie66** [happypeter/haoqi_alipay#7]
看看 http://haoqicat.com/happypeter/zhi-fu-bao-shou-kuan-ji-cheng

给 Peter 提提意见。然后研究一下能不能在自己的站内获取到用户的收货地址，如果可以，那

shop.haoduoshipin.com 就可以采取站内集成的方式来用自己的网页卖货了。

如果不行，那就让用户去支付宝登陆。

**Comment by billie66** [comment]
现在支付宝双功能收款服务已经下架了，对于个人用户只能使用担保交易

**Comment by billie66** [comment]
支付宝技术支持页面仍然提供双功能收款开发包

**Comment by billie66** [comment]
就我个人而言，这门课程对我是很帮助的，看完之后，基本就明白整个支付流程了，再读文档能节省很多时间。

**Comment by billie66** [comment]
好奇猫已经使用担保交易了。

支付宝目前没有提取用户私人信息的接口。在担保交易中，若不设置下面四个请求参数：

```
      receive_address
      receive_name
      receive_zip
      receive_mobile
```
在买家付款的时候，会要求其填写收货地址、姓名、邮编、手机号，不过这也太不方便了

**Comment by happypeter** [comment]
那既然拿不到 receive_address ，如何设置呢？

**Comment by billie66** [comment]
担保交易，上面四个参数随意填写个值就行了

**Comment by happypeter** [comment]
明白
